// THIS FILE IS AUTOGENERATED BY codegen.py
// DO NOT MODIFY THIS FILE DIRECTLY. YOUR CHANGES WILL BE OVERWRITTEN.

static NSString* const PreferencesIdentifier = @"com.example.9 (ls).preferences";
static NSString* const PreferencesReloadNotification = @"9 (ls).preferences.reload";

static BOOL EnabledPreference = NO;

static void LoadPreferences() {
    NSUserDefaults* preferences = [[NSUserDefaults alloc] initWithSuiteName:PreferencesIdentifier];
    if (!preferences) return;

    EnabledPreference = [[preferences objectForKey:@"EnabledPreference"] boolValue];
}
